#! /bin/bash
set -euo pipefail

help() {
	cat <<EOF
We have seen cases where we needed to manually re-trigger the printing of the
labels. What it does to re-print is remove the Printed=True condition.

This command uses the namespace "default", and currently doesn't support
changing to a different namespace.

Usage:
  $(basename "$0") <email | certname>
EOF
}

if ! [ $# -eq 1 ]; then
	printf "error: you need to give an email or a Certificate name as argument.\n" >&2
fi
emailOrName=$1

certName=
if [[ $emailOrName == *@* ]]; then
	email=$(echo "$emailOrName" | tr @ -)
	certName=$(kubectl get cert -l email="$email" -oname)
	if [[ -z $certName ]]; then
		echo "No certificate found for label email=$email"
		exit 1
	fi
else
	certName=$(kubectl get cert "$emailOrName" -oname)
	if [[ -z $certName ]]; then
		echo "Certificate $emailOrName not found"
		exit 1
	fi
fi

kubectl patch "$certName" --subresource status --type=json -p '[{"op":"replace","path":"/status/conditions","value":[{"type":"Printed","status":"False"}]}]'
